#! /bin/bash

docker run --rm -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /home/hybris/Downloads:/home/hybris/Downloads \
    -p 8080:8080 trantor:vlc \
    cvlc -I http --http-password foobar $PWD/${@/ / $PWD\/} vlc://quit > /tmp/vlc.log 2>&1
